version: '3.8'
services:
  react:
    image: react-app:1.0
    container_name: react-app
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "4500:4500"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./client:/app:delegated"
      - /app/node_modules

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:80"
    image: laravel-app:1.0
    volumes:
      - ./:/usr/share/nginx
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
