version: '3.8'

services:

  # CLIENT APP
  client:
    image: react-app:1.0
    container_name: react-app
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./client:/app:delegated"
      - /app/node_modules

  # WEB SERVER
  php-fpm:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./api:/var/www
    networks:
      - laravel

  # NGINX
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
